apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: ingress-node-firewall-daemon-metrics-certs
  creationTimestamp: null
  labels:
    app: ingress-node-firewall-daemon
    control-plane: daemon
  name: ingress-node-firewall-daemon-metrics
spec:
  clusterIP: None
  ports:
  - name: metrics
    port: 9301
    protocol: TCP
    targetPort: https
  publishNotReadyAddresses: true
  selector:
    app: ingress-node-firewall-daemon
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
