# permissions for end users to edit ingressnodefirewallnodestates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ingressnodefirewallnodestate-editor-role
rules:
- apiGroups:
  - ingressnodefirewall.openshift.io
  resources:
  - ingressnodefirewallnodestates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ingressnodefirewall.openshift.io
  resources:
  - ingressnodefirewallnodestates/status
  verbs:
  - get
