# Unable to modify role.yaml so anything extra can be added here
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-cluster-role-extra
rules:
  - apiGroups:
      - authentication.k8s.io
    resources:
      - tokenreviews
    verbs:
      - create
  - apiGroups:
      - authorization.k8s.io
    resources:
      - subjectaccessreviews
    verbs:
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: daemon-clusterrole-extra
rules:
  - apiGroups:
      - authentication.k8s.io
    resources:
      - tokenreviews
    verbs:
      - create
  - apiGroups:
      - authorization.k8s.io
    resources:
      - subjectaccessreviews
    verbs:
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: daemon-role-extra
  namespace: system
rules:
  - apiGroups:
      - ingressnodefirewall.openshift.io
    resources:
      - ingressnodefirewallnodestates
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ingressnodefirewall.openshift.io
    resources:
      - ingressnodefirewallnodestates/finalizers
    verbs:
      - update
  - apiGroups:
      - ingressnodefirewall.openshift.io
    resources:
      - ingressnodefirewallnodestates/status
    verbs:
      - get
      - patch
      - update
