apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: ingress-node-firewall-daemon-role-extra
rules:
- apiGroups:
  - ingressnodefirewall.openshift.io
  resources:
  - ingressnodefirewallnodestates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ingressnodefirewall.openshift.io
  resources:
  - ingressnodefirewallnodestates/finalizers
  verbs:
  - update
- apiGroups:
  - ingressnodefirewall.openshift.io
  resources:
  - ingressnodefirewallnodestates/status
  verbs:
  - get
  - patch
  - update
