apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: ingress-node-firewall-controller-manager-metrics-certs
  creationTimestamp: null
  labels:
    control-plane: controller-manager
  name: ingress-node-firewall-controller-manager-metrics
spec:
  clusterIP: None
  ports:
  - name: metrics
    port: 9300
    protocol: TCP
    targetPort: https
  publishNotReadyAddresses: true
  selector:
    control-plane: controller-manager
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
