apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: ingress-node-firewall-daemon-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ingress-node-firewall-daemon-role-extra
subjects:
- kind: ServiceAccount
  name: ingress-node-firewall-daemon
  namespace: openshift-ingress-node-firewall
