apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: ingress-node-firewall-daemon
  name: ingress-node-firewall-daemon
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    interval: 30s
    port: metrics
    scheme: https
    tlsConfig:
      caFile: /etc/prometheus/configmaps/serving-certs-ca-bundle/service-ca.crt
      serverName: ingress-node-firewall-daemon-metrics.openshift-ingress-node-firewall.svc
  jobLabel: app
  selector:
    matchLabels:
      app: ingress-node-firewall-daemon
