kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: kpng-proxy
networking:
  kubeProxyMode: "none"
  apiServerAddress: "0.0.0.0"
  disableDefaultCNI: false
  podSubnet: 192.168.0.0/16
nodes:
  - role: control-plane
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "kube-proxy=kpng"
            authorization-mode: "AlwaysAllow"
  - role: worker
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "kube-proxy=kpng"
  - role: worker
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "kube-proxy=kpng"
