apiVersion: v1
kind: Namespace
metadata:
  name: openshift-ingress-node-firewall
---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ingress-node-firewall-operator-index
  namespace: openshift-marketplace
spec:
  displayName: CI Index
  image: image-registry.openshift-image-registry.svc:5000/openshift-marketplace/ingress-node-firewall-operator-index:latest
  publisher: Red Hat
  sourceType: grpc
  updateStrategy:
    registryPoll:
      interval: 10m0s
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: ingress-node-firewall-operator
  namespace: openshift-ingress-node-firewall
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ingress-node-firewall-operator-subscription
  namespace: openshift-ingress-node-firewall
spec:
  channel: "alpha"
  name: ingress-node-firewall
  source: ingress-node-firewall-operator-index
  sourceNamespace: openshift-marketplace
